
services:

  db:
    image: mysql:8.0
    container_name: verification_db_mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d

    ports:
      - "3307:3306"
    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      timeout: 20s
      retries: 10

  # The Redis service
  redis:
    image: redis:6.2-alpine 
    container_name: verification_redis
    ports:
      - "6379:6379" # Map the container's port 6379 to your host machine's port 6379
    volumes:
      - redis_data:/data 

  web:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: verification_web
    command: python manage.py runserver 0.0.0.0:8000 # The command to start the server
    volumes:
      - .:/app # Mount your local code into the container for live-reloading
      - media_volume:/app/media # Persist uploaded files
      - ../docker_data:/data
    ports:
      - "8000:8000" # Map container port 8000 to host port 8000
    env_file:
      - .env 
    depends_on:
      - redis 

  celery:
    build: . 
    container_name: verification_celery
    command: celery -A localrun worker -l info
    volumes:
      - .:/app 
      - media_volume:/app/media 
      - ../docker_data:/data
    env_file:
      - .env 
    depends_on:
      - redis 

volumes:
  mysql_data:
  redis_data:
  media_volume: