# Generated by Django 5.1.6 on 2025-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerificationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Log messages or error details.",
                        null=True,
                    ),
                ),
                (
                    "report_file_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
